[package]
name = "esp32-homecontrol"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-backtrace = { version = "0.14.1", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "0.22.0", features = ["esp32s3", "log"] }
esp-alloc = { version = "0.5.0" }
embassy-net = { version = "0.5.0", features = [
    "tcp",
    "udp",
    "dns",
    "dhcpv4",
    "log",
    "dhcpv4-hostname",
] }

mipidsi = { version = "0.9.0" }
esp-wifi = { version = "0.11.0", default-features = false, features = [
    "esp32s3",
    "serde",
    "wifi",
    "esp-alloc",
    "log",
] }
heapless = { version = "0.8.0", default-features = false }
esp-println = { version = "0.12.0", features = ["esp32s3", "log"] }
log = { version = "0.4.21" }
embassy-executor = { version = "0.6.0", features = [
    "task-arena-size-163840",
    "log",
] }
embassy-time = { version = "0.3.1", features = [] }
esp-hal-embassy = { version = "0.5.0", features = [
    "esp32s3",
    "integrated-timers",
] }
rust-mqtt = { version = "0.3.0", default-features = false, features = [] }
rand_core = "0.6.4"
embedded-text = "0.7.2"
embedded-graphics = { version = "0.8.1", features = [] }
embedded-hal = { version = "1.0.0", features = [] }
dht11 = "0.3.1"
serde = { version = "1.0.215", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.133", default-features = false, features = [
    "alloc",
] }
embassy-futures = { version = "0.1.1", features = [] }
embassy-sync = { version = "0.6.0", features = [] }
static_cell = "2.1.0"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
